### ISSUE TITLE
About the net_patch model.

### ISSUE THREAD

**Issue by aa1234241** [MIRACLE-Center/Oneshot_landmark_detection#11]
Hello, thanks for your excellent work!
I have a question about the SSL training. It seems that it involves two model. One for the original image, another is for the patch image. I want to know why the original image and the patched image can not share the same model.  Also,  the patch model seems not used at the test time.

**Comment by qsyao** [comment]
It requires a siamese Network for contrastive learning which shares the same arch with different initial parameters.
