### ISSUE TITLE
Request for Source Papers for Methods in the Folder `script_sota`

### ISSUE THREAD

**Issue by Djanghao** [MIRACLE-Center/Oneshot_landmark_detection#12]
Hello, 

Thank you for your outstanding work!

I am reviewing the methods implemented in folder [`script_sota`](https://github.com/MIRACLE-Center/Oneshot_landmark_detection/tree/main/code/cc2d-final/scripts_sota) and would like to know from which specific papers each of the ERE, Heatmap, SAM and Voting originates. Are these methods derived from the papers that you compared with your proposed method?

Thank you for your attention to this matter. I look forward to your response.

**Comment by qsyao** [comment]
Yes, these are the baselines listed in our paper. 

ERE: CVPR 22
SAM: TMI 22
Voting: Chen et al.
